### ISSUE TITLE
OpenLens-6.4.2.amd64.deb does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [MuhammedKalkan/OpenLens#132]
Can not run from deb package on Ubuntu 18.04.
Deb binaries require newer glibc, than Ubuntu has:

```
ldd /opt/OpenLens/resources/app.asar.unpacked/node_modules/@k8slens/core/node_modules/node-pty/build/Release/pty.node

/opt/OpenLens/resources/app.asar.unpacked/node_modules/@k8slens/core/node_modules/node-pty/build/Release/pty.node:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /opt/OpenLens/resources/app.asar.unpacked/node_modules/@k8slens/core/node_modules/node-pty/build/Release/pty.node)
        linux-vdso.so.1 (0x00007ffcb61c1000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fdd530be000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdd52d35000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdd52b16000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdd52725000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdd52387000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdd532c1000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdd5216f000)
```

but there is 2.27 version in Ubuntu 18.04:
```
$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
```

## Details
<details>
<summary>Complete error message</summary>

```
$ open-lens
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/unixTerminal.js
- /opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/index.js
- /opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js
- /opt/OpenLens/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/index.js',
    '/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js',
    '/opt/OpenLens/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /opt/OpenLens/resources/app.asar.unpacked/node_modules/@k8slens/core/node_modules/node-pty/build/Release/pty.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
```
</details>

**Comment by jkroepke** [comment]
Hi,

we do not support Ubuntu 18.04 and its [EOL](https://endoflife.date/ubuntu) in 3 weeks anyways.
